### ISSUE TITLE
Github API rate limit reached

### ISSUE THREAD

**Issue by tmjee** [jcabi/jcabi-github#1180] opened 2015-10-08 09:34 UTC
while removing a @todo from issue #1017 I am getting this in travis

```
[INFO] {"message":"API rate limit exceeded for 52.0.240.122. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}>
[INFO] 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
[INFO] 	at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:117)
[INFO] 	at com.jcabi.github.RtValuePagination$Items.fetch(RtValuePagination.java:199)
[INFO] 	at com.jcabi.github.RtValuePagination$Items.hasNext(RtValuePagination.java:185)
[INFO] 	at script1.run(script1.groovy:11)
[INFO] 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:518)
[INFO] 	at org.codehaus.gmaven.adapter.impl.ScriptExecutorImpl.execute(ScriptExecutorImpl.java:80)
[INFO] 	at org.codehaus.gmaven.plugin.ExecuteMojo$1.run(ExecuteMojo.java:100)
[INFO] 	at org.codehaus.gmaven.plugin.util.SystemNoExitGuard.run(SystemNoExitGuard.java:45)
[INFO] 	at org.codehaus.gmaven.plugin.ExecuteMojo.run(ExecuteMojo.java:96)
[INFO] 	at org.codehaus.gmaven.plugin.MojoSupport.execute(MojoSupport.java:45)
[INFO] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[INFO] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
[INFO] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
[INFO] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
[INFO] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
[INFO] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
[INFO] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:606)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ..FAILED (4.9 s)
```

**Comment by dmarkov** [comment] 2015-10-13 08:53
@yegor256 dispatch this issue please

**Comment by yegor256** [comment] 2015-10-14 20:59
@tmjee I believe it's a duplicate of #1175

**Closed** 2015-10-14 20:59 UTC
Labels: duplicate, invalid
