### ISSUE TITLE
RtRepoITCase#iteratesLanguages fails on Rultor

### ISSUE THREAD

**Issue by dpisarenko** [jcabi/jcabi-github#1007] opened 2015-01-28 11:08 UTC
When trying to merge PR https://github.com/jcabi/jcabi-github/pull/985 , following test failed:

```
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.936 sec <<< FAILURE! - in com.jcabi.github.RtRepoITCase iteratesLanguages(com.jcabi.github.RtRepoITCase) Time elapsed: 0.301 sec <<< FAILURE! 
java.lang.AssertionError: Expected: not an empty iterable but: was <[]> at 
org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20) at 
org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8) at 
com.jcabi.github.RtRepoITCase.iteratesLanguages(RtRepoITCase.java:163)
```

That same test does not fail in Travis CI.

**Comment by yegor256** [comment] 2015-01-29 17:30
duplicate of #1002

**Closed by yegor256** 2015-01-29 17:30 UTC
