### ISSUE TITLE
Missing Atribute.

### ISSUE THREAD

**Issue by GIAPB** [jcabi/jcabi-github#1270] opened 2017-01-18 21:13 UTC
Everything works while in eclipse. The only problem is,
when exported, the console throws this error: 
```C:\Users\matthew\Desktop>java -jar GIAPB.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail
s.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at xyz.lexium.giapb.GIAPB.main(GIAPB.java:22)
Caused by: java.lang.IllegalArgumentException: Attribute 'JCabi-Version' not fou
nd in MANIFEST.MF file(s) among 3 other attribute(s): ["Class-Path", "Main-Class
", "Manifest-Version"]
        at com.jcabi.manifests.Manifests.read(Manifests.java:274)
        at com.jcabi.github.RtGithub.<clinit>(RtGithub.java:82)
        ... 1 more

C:\Users\matthew\Desktop>
```

**Comment by 0crat** [comment] 2017-01-18 21:13
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment] 2017-01-19 09:52
@GIAPB how do you package your app? It seems that you delete that valuable `META-INF/MANIFEST.MF` that is supposed to be packaged together with all classes from jcabi-github.jar

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-20 13:09
It in in xyz.lexium.giapb. Nothig else is changed. Just compiled via eclipse

**Comment by yegor256** [comment] 2017-01-27 20:12
@xXXIMMATTHEWXXx I'm afraid that "compile via eclipse" is what broke the structure of the JAR file. Try to package with Maven.

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-27 20:19
Thanks

**Comment by amihaiemil** [comment] 2017-04-15 11:35
@GIAPB  @xXXIMMATTHEWXXx The problem is that the library reads some attributes from its Manifest.MF file. This causes troubles when it is packaged in a ``.war`` for instance. You can solve this issue with ``maven-assembly-plugin``. Here's how I did it: https://github.com/jcabi/jcabi-github/issues/1198#issuecomment-225122003 .

There is also an issue open, to change this mechanism; https://github.com/jcabi/jcabi-github/issues/1246

**Comment by amihaiemil** [comment] 2018-12-05 07:43
This has been fixed in [release 0.37](https://github.com/jcabi/jcabi-github/issues/1373).

**Closed by amihaiemil** 2018-12-05 07:43 UTC

**Comment by 0crat** [comment] 2018-12-05 09:17
Job `gh:jcabi/jcabi-github#1270` is not assigned, can't get performer
