### ISSUE TITLE
Incomplete integration tests javadoc

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-github#975] opened 2015-01-11 00:39 UTC
In the light of #963 it would probably be useful to include required oauth scopes in integration tests javadoc.

**Comment by yegor256** [comment] 2015-01-11 08:16
@maurezen let's wait for #963 completion and then review this bug again

**Comment by maurezen** [comment] 2015-01-13 16:02
@yegor256 it's time to review this again.

**Comment by yegor256** [comment] 2015-01-13 16:17
@maurezen yes, looks like a valid bug, thanks

**Comment by dmarkov** [comment] 2015-01-20 09:01
@jenya this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmarkov** [comment] 2015-01-21 07:49
@maurezen thanks a lot for reporting, **15 mins** added to your acc, pmt ID `50566522`

**Comment by dmarkov** [comment] 2015-01-21 13:29
@dpisarenko the issue is yours, please help

**Comment by dpisarenko** [comment] 2015-01-21 19:41
@maurezen Where can I find the actual integration tests (which require OAuth) ? In `src/it` I only find `Sample` and `SampleTest`, which don't look like real tests.

**Comment by maurezen** [comment] 2015-01-21 21:41
@dpisarenko that's because integration tests are in `tests` directory, have you looked there?
`src/test/java/com/jcabi/github/*IT*` . Another way you could have found them is looking for the `failsafe.github.*` properties usage. Does that make sense?

**Comment by dpisarenko** [comment] 2015-01-23 10:55
@maurezen  Thanks. Is it correct that the result of this task is a table with 2 columns:

  1. Integration test method, e. g. `com.jcabi.github.RtMarkdownITCase#rendersMarkdown` and
  1. OAuth scope required to run this method, e. g. none in case of `com.jcabi.github.RtMarkdownITCase#rendersMarkdown`

(for all integration test methods in the project) ?

**Comment by maurezen** [comment] 2015-01-23 12:11
@dpisarenko the table should be much less, that is - IT class vs a list of OAuth scopes required for it. It should be in the test package javadoc. The information about each IT test class should be duplicated in its own javadoc.

**Comment by dpisarenko** [comment] 2015-01-28 11:01
@dmarkov Please find someone to review PR https://github.com/jcabi/jcabi-github/pull/1005 .

**Comment by krzyk** [comment] 2015-01-28 13:01
@maurezen I think that there is no point of duplicating information in package level javadoc, moreover it doesn't give much information for me as a developer. More usefull would be to have clear information in README.md which scopes I need to have in my single API key to have all the test pass.

**Comment by dpisarenko** [comment] 2015-01-29 11:39
@maurezen What do you think of @krzyk 's comment regarding duplication of information?

**Comment by maurezen** [comment] 2015-01-30 17:19
@dpisarenko @krzyk I agree that having a summary in `README.md` would be fine. Details are still needed, IMO.

**Comment by krzyk** [comment] 2015-01-30 18:53
@maurezen details in method javadocs, but there is no point in duplicating this information in package javadoc

**Comment by maurezen** [comment] 2015-01-31 14:27
@krzyk the work is already done, we might as well have it. no point in scrapping the overview, isn't it?

**Comment by krzyk** [comment] 2015-01-31 15:00
@maurezen It is not work done right now, but all the future work on supporting two places (or actually three, README.md is the most important here, but there we don't need it per test) with the same information

**Comment by maurezen** [comment] 2015-02-01 21:06
@krzyk okay, agreed.

**Comment by dmarkov** [comment] 2015-02-21 01:14
@nhekfqn the issue is yours, please help

**Comment by dmarkov** [comment] 2015-05-20 07:20
@super132 the task is yours please proceed

**Comment by super132** [comment] 2015-05-26 00:19
@maurezen PR #1083 fixed this issue. Would you please close this ticket? Thanks.

**Comment by super132** [comment] 2015-05-27 08:52
@dmarkov If @maurezen does not show up to close this ticket, how will this be handled? I have been losing fast delivery bonus due to the responsiveness of different parties. Thanks.

**Comment by dmarkov** [comment] 2015-05-27 08:57
@maurezen once `975-0a524603`/#1093 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by super132** [comment] 2015-05-27 09:05
@dmarkov , could you please advise my payment details regarding to this ticket? Thanks.

**Closed** 2015-05-27 09:21 UTC
Labels: 30 mins, @super132, bug, DEV

**Comment by dmarkov** [comment] 2015-05-28 12:24
@super132 **30 mins** added to your account (payment number `AP-74E21841MM490374N`), many thanks for your contribution! 171 hours and 6 mins spent here.... +30 added to your rating, current score is: [+271](http://www.netbout.com/b/35282?open=rating)

**Comment by 0pdd** [comment] 2022-07-05 19:44
@maurezen the puzzle [#1563](https://github.com/jcabi/jcabi-github/issues/1563) is still not solved.
