### ISSUE TITLE
authentificated Github API calls in tests

### ISSUE THREAD

**Issue by dmzaytsev** [jcabi/jcabi-github#1176] opened 2015-10-01 08:43 UTC
sometimes unit tests failed with the error
```
{"message":"API rate limit exceeded for 52.0.240.122.
 (But here's the good news: Authenticated requests get a higher rate limit. 
Check out the documentation for more details.)",
"documentation_url":"https://developer.github.com/v3/#rate-limiting"}>
```
see Travis log https://travis-ci.org/jcabi/jcabi-github/jobs/83011585 for instance

I would suggest to use authentificated Github API calls in tests
it possible create personal access token without any right(or create an new github account and then create a token)
in API calls token can be used in `Authorization` header
like this 
`Authorization: Basic TOKEN`

**Comment by dmarkov** [comment] 2015-10-05 08:11
@yegor256 please dispatch this issue

**Comment by yegor256** [comment] 2015-10-05 18:09
@dmzaytsev duplicate of #1175

**Closed by yegor256** 2015-10-05 18:09 UTC
