### ISSUE TITLE
duplicate validations on interface & implementation

### ISSUE THREAD

**Issue by simonjenga** [jcabi/jcabi-github#1121] opened 2015-06-13 08:27 UTC
Why are there duplicate validations on both an Interface and it's implementation.

**Comment by dmarkov** [comment] 2015-06-15 08:35
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment] 2015-06-23 20:46
@simonjenga what validations are you talking about? Can you give an example?

**Comment by simonjenga** [comment] 2015-07-04 10:35
@yegor256 

Interface: ```com.jcabi.github.Github```

```
@NotNull(message = "request is never NULL")
Request entry();

@NotNull(message = "list of repositories is never NULL")
 Repos repos();

@NotNull(message = "gists is never NULL")
Gists gists();

@NotNull(message = "markdown API is never NULL")
Markdown markdown();
```

Implementation: ```com.jcabi.github.RtGithub```

```
@Override
@NotNull(message = "request can't be NULL")
public Request entry() {
       // method details
}

@Override
@NotNull(message = "repos is never NULL")
public Repos repos() {
        // method details
}

@Override
@NotNull(message = "gists are never NULL")
public Gists gists() {
        // method details
}

@Override
@NotNull(message = "Markdown is never NULL")
public Markdown markdown() {
        // method details
}
```

**Comment by yegor256** [comment] 2015-07-07 05:44
@simonjenga make sense, but these annotations play different roles. The annotations on interfaces are declarative. They don't check anything in runtime, just inform users about our promises. Annotation on class methods are validated in runtime. So, it's by design, no need to fix.

**Comment by dmarkov** [comment] 2015-07-07 08:43
@yegor256 don't close it, ask @simonjenga to do do it, since he created it, thanks!

**Closed** 2015-07-07 17:30 UTC
Labels: invalid

**Comment by simonjenga** [comment] 2015-07-07 19:10
@yegor256 It seems to me you closed it. I could have done but i wanted to raise an issue. Please help in resolving it. Why is it that @dmarkov communicates at his own convenience? It's bad to ignore some things. I tried to communicate to him before and he never responded https://github.com/jcabi/jcabi-aether/issues/57 That issue together with it's fix were never paid. This issue https://github.com/jcabi/jcabi-log/issues/58 too and also it's fix were also never paid.

However, this issue https://github.com/yegor256/takes/issues/148 and it's fix were paid. What criteria was used to arrive to that and what qualifies for pay or not. Is it some form of favoritism, prejudice, discrimination etc. It have seen it happen before but i think this is the right time to talk about it.

It would be good to clearly communicate to it before wrong conclusions are made.

**Comment by yegor256** [comment] 2015-07-08 04:00
@simonjenga in general, the workflow is this: 1) you report a bug, 2) project architect accepts it ([par.21](http://www.teamed.io/policy.html#21)) or rejects ([par.13](http://www.teamed.io/policy.html#13)), 3) you're paid for its reporting ([par.12](http://www.teamed.io/policy.html#12)), 4) someone is assigned as a developer, 5) the bug is fixed and the developer is paid. Make sense?

**Comment by simonjenga** [comment] 2015-07-08 08:09
@yegor256 Makes sense. Have you also ever considered that over reliance on one person (project architect) for all decisions may at one time be detrimental to the project? What if this person is unavailable for various reasons (sickness, vacation, jailed)? That would make the project to halt.
What if also the said person has personal issues with Developer X? it now means Developer X will have a hard time in the project and may even opt to exit the project.

**Comment by yegor256** [comment] 2015-07-10 02:01
@simonjenga you're right, all this may happen, but I believe in monarchy in software development, not democracy. Every decision has to be made by a single person and this person has to be responsible for it. Even if he is wrong, we trust him/her for the time he/she is an architect. We can always replace this person, but until then, we obey. More about it here: http://www.yegor256.com/tag/architect.html
